# YAML Config file for RTM-QL agent

learning_params:
  gamma: 1
  EDF:
    epsilon_min: 0.01
    epsilon_max: 1.0
    epsilon_decay: 0.99
  SEDF:
    tail: 0.3
    slope: 0.3
    tail_gradient: 0.01
  epsilon_decay_function: SEDF 

memory_params:
  memory_size: 10000
  batch_size: 30

game_params:
  episodes: 300
  reward: 1
  max_score: 200
  action_space: 2

qrtm_params:
  number_of_clauses: 1000
  T: 1000
  s: 2.75
