# YAML Config file for RTM-QL agent

learning_params:
  learning_rate: 0.01
  gamma: 1
  EDF:
    epsilon_min: 0.01
    epsilon_max: 1.0
    epsilon_decay: 0.99
  SEDF:
    tail: 0.4
    slope: 0.2
    tail_gradient: 0.2
  epsilon_decay_function: SEDF 

memory_params:
  memory_size: 10000
  batch_size: 25

game_params:
  episodes: 100
  reward: 0
  max_score: 1
  action_space: 2

qrtm_params:
  # number_of_features = num_inputs [in this case, 4] * feature_length ALWAYS
  number_of_features: 1
  feature_length: 3
  # number_of_clauses = 2 * T ALWAYS
  number_of_clauses: 200
  T: 100
  s: 0.000001
  incremental: True
  weighted_clauses: False

preproc_params:
  # Binarizer has to be a string 
  # G: Greater Than binarizer 
  # B: Binned binarizer
  # Q: Quartile binarizer
  # U: Unsigned binarizer
  # S: Simple binarizer ** DEFAULT feature length should be set to 2 and number of features to 8
  binarizer: U
